#!/bin/sh

ls -l ./cache
export G_SLICE=always-malloc
export G_DEBUG=gc-friendly
/usr/bin/valgrind \
	--leak-check=full \
	--suppressions=suppressions/pango.supp \
	--suppressions=suppressions/glib.supp \
	--suppressions=suppressions/mesa.supp \
	--gen-suppressions=yes \
	$@ ./cache
