#!/bin/sh

PROG=./cache
PROG=./view_plus
PROG=./hires
PROG="./res_vhi -n"
PROG=./pixbuf
PROG=./resources
PROG=./frame_rate
PROG=./actor_plus
PROG=./promise
PROG=./glx
PROG=./list
PROG=./actor_no_scene
PROG=./waveform_test

ls -l $PROG
export G_SLICE=always-malloc
export G_DEBUG=gc-friendly

/usr/bin/valgrind \
	-s \
	--leak-check=full \
	--suppressions=../lib/agl/test/suppressions/mesa.supp \
	--suppressions=suppressions/pango.supp \
	--suppressions=suppressions/glib.supp \
	--suppressions=suppressions/gtk4.supp \
	--suppressions=suppressions/mesa.supp \
	--suppressions=suppressions/test.supp \
	--gen-suppressions=yes \
	--num-callers=50 \
	$@ $PROG
