#!/bin/bash

out=shaders.c
echo "" > $out

function a {
	echo '' >> $out
	echo 'WfShaderText '$1'_text = {" \' >> $out
	cpp -P $1.vert | sed -e "s/$/ \\\/" >> $out
	echo '",' >> $out
	echo '" \' >> $out
	cpp -P $1.frag | sed -e "s/$/ \\\/" >> $out
	echo '"' >> $out
	echo '};' >> $out
}

a "peak"
a "horizontal"
a "vertical"
a "hires"
a "alpha_map"
a "ruler"
a "texture_2d"

